# Generated by Django 3.1.2 on 2020-10-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='imgs')),
                ('prize1', models.IntegerField()),
                ('prize2', models.IntegerField()),
                ('season', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('food', models.BooleanField(default=True)),
            ],
        ),
    ]
