# Generated by Django 3.1.2 on 2020-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20201014_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
