# Generated by Django 3.1.2 on 2020-10-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20201014_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='food',
            field=models.BooleanField(default=False),
        ),
    ]
