# Generated by Django 3.1.2 on 2020-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20201014_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='prize1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='prize2',
        ),
        migrations.AddField(
            model_name='destination',
            name='maxprize',
            field=models.IntegerField(default=20, verbose_name='Maximum 15 persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='minprize',
            field=models.IntegerField(default=20, verbose_name='Miniumum 4 persons'),
            preserve_default=False,
        ),
    ]
