# Generated by Django 3.1.2 on 2020-10-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_auto_20201019_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='maxprize',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='minprize',
        ),
        migrations.AddField(
            model_name='destination',
            name='bus',
            field=models.IntegerField(default=0, verbose_name='Air Bus Prize (42 people)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='car',
            field=models.IntegerField(default=0, verbose_name='Car Prize (4 people)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='trav',
            field=models.IntegerField(default=0, verbose_name='Traveller Prize (24 people)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='van',
            field=models.IntegerField(default=0, verbose_name='Mini-Van Prize (12 people)'),
            preserve_default=False,
        ),
    ]
