# Generated by Django 3.1.2 on 2020-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_auto_20201019_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='imgs')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='destination',
            name='description2',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='description3',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
