# Generated by Django 3.1.2 on 2020-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_auto_20201019_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description3',
        ),
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='review',
            field=models.TextField(),
        ),
    ]
