# Generated by Django 3.1.2 on 2020-10-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_auto_20201019_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonials',
            new_name='Testimonial',
        ),
    ]
