# Generated by Django 3.1.2 on 2020-10-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_auto_20201019_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('pkg', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
