# Generated by Django 3.1.2 on 2020-10-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pkg',
            new_name='package',
        ),
    ]
