# Generated by Django 3.1.2 on 2020-10-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_auto_20201020_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='banner1',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='banner2',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='banner3',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='banner4',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='banner5',
            field=models.ImageField(default=0, upload_to='imgs'),
            preserve_default=False,
        ),
    ]
