# Generated by Django 3.1.2 on 2020-10-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_enquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Enquirie',
        ),
    ]
