# Generated by Django 3.1.2 on 2020-10-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_auto_20201021_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirie',
            old_name='messsage',
            new_name='message',
        ),
    ]
