# Generated by Django 3.1.2 on 2020-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_auto_20201022_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirie',
            name='urgent',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
